[package]
edition = "2021"
name = "clock"
version = "0.1.0"
authors = ["Matthias Beyer <mail@beyermatthias.de>"]
resolver = "2"
#rust-version = "1.76"

[dependencies]
cortex-m = { version = "0.7.7", features = ["inline-asm"] }
cortex-m-rt = "0.7.3"
defmt = "0.3"
defmt-rtt = "0.4"
embedded-graphics = { version = "0.8.1", features = ["defmt"] }
embedded-hal-1 = { package = "embedded-hal", version = "1.0.0" }
embedded-hal-async = "1.0"
embedded-hal-bus = { version = "0.1.0", features = ["async"] }
embedded-io-async = { version = "0.6.1", features = ["defmt-03"] }
embedded-menu = "0.6.1"
fixed = "1.23.1"
fixed-macro = "1.2"
heapless = "0.8"
log = "0.4"
panic-probe = { version = "0.3", features = ["print-defmt"] }
pio = "0.2.1"
pio-proc = "0.2"
portable-atomic = { version = "1.5", features = ["critical-section"] }
rand = { version = "0.8.5", default-features = false }
smart-leds = "0.4.0"
ssd1306 = "0.8.4"
static_cell = "2"
usbd-hid = "0.8.0"

[dependencies.embassy-embedded-hal]
version = "0.2.0"
git = "https://github.com/embassy-rs/embassy.git"
features = [
    "defmt",
]

[dependencies.embassy-sync]
version = "0.6.0"
git = "https://github.com/embassy-rs/embassy.git"
features = [
    "defmt",
]

[dependencies.embassy-executor]
version = "0.6.3"
git = "https://github.com/embassy-rs/embassy.git"
features = [
    "arch-cortex-m",
    "executor-thread",
    "executor-interrupt",
    "defmt",
    "integrated-timers",
    "task-arena-size-8192",
]

[dependencies.embassy-time]
version = "0.3"
git = "https://github.com/embassy-rs/embassy.git"
features = [
    "defmt",
    "defmt-timestamp-uptime",
]

[dependencies.embassy-rp]
version = "0.2.0"
git = "https://github.com/embassy-rs/embassy.git"
features = [
    "defmt",
    "unstable-pac",
    "time-driver",
    "critical-section-impl",
    "rp2040",
]

[dependencies.embassy-futures]
version = "0.1.0"
git = "https://github.com/embassy-rs/embassy.git"

[dependencies.embassy-usb]
version = "0.3.0"
git = "https://github.com/embassy-rs/embassy.git"
features = [ "defmt" ]

[dependencies.futures]
version = "0.3.17"
default-features = false
features = [
    "async-await",
    "cfg-target-has-atomic",
    "unstable",
]

[profile.release]
debug = 2

[profile.dev.package."*"]
opt-level = 3
